### ISSUE TITLE
Signed Certificate Issue

### ISSUE THREAD

**Issue by denniswritescode** [Koshukey/techcrunch-cli#1]
Installed via npm and ran the command `tc top` and the following error occurred:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

Any thoughts on what's going on?

**Comment by Koshukey** [comment]
First, thanks for reporting issue 😀

I will check it soon !
